@declarationsId=4a6d4dff-7edf-4e20-a9dc-5c57df1f458a
@memberId=9b376281-b478-4c0a-a61e-06c476838dfe
@paymentId=10241b64-e09a-4cad-93ea-348c89da7009
@contributionId=REPLACE_WITH_CONTRIBUTION_ID
@userId=7e534916-ffcc-467a-811a-b2544840777d

### ----------------- DECLARATIONS ------------------

###
# @name createDeclaration
POST {{NEXT_PUBLIC_API_BASE_URL}}/contributions/declarations
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{ 
  "amount":100
}

###
# @name getMyDeclarations
GET {{NEXT_PUBLIC_API_BASE_URL}}/contributions/declarations
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

###
# @name getAllDeclarations
GET {{NEXT_PUBLIC_API_BASE_URL}}/contributions/all-declarations
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

###
# @name approveDeclaration
POST {{NEXT_PUBLIC_API_BASE_URL}}/contributions/declarations/{{declarationsId}}/approve
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

###
# @name rejectDeclaration
POST {{NEXT_PUBLIC_API_BASE_URL}}/contributions/declarations/{{declarationsId}}/reject
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

### ----------------- PAYMENTS ------------------

###
# @name manualContributionPayment
POST {{NEXT_PUBLIC_API_BASE_URL}}/contributions/record
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{ 
   "amount":100,
   "paymentMethod":"CASH",
   "memberId":"{{memberId}}"
}

###
# @name verifyContributionPayment
POST {{NEXT_PUBLIC_API_BASE_URL}}/contributions/payments/{{paymentId}}/verify
Content-Type: application/json
Authorization: Bearer {{TOKEN}
###
# @name getContributions
GET {{NEXT_PUBLIC_API_BASE_URL}}/payments/contributions
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

###
# @name getMyContributions
GET {{NEXT_PUBLIC_API_BASE_URL}}/contributions/my
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

###
# @name generateContributions
POST {{NEXT_PUBLIC_API_BASE_URL}}/contributions
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "year": 2026,
  "month": 5
}

###
# @name waiveContribution
PATCH {{NEXT_PUBLIC_API_BASE_URL}}/contributions
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "contributionPeriodId": "REPLACE_WITH_UUID",
  "reason": "Hardship case"
}

###
# @name getUserContributions
GET {{NEXT_PUBLIC_API_BASE_URL}}/contributions/users/{{userId}}
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

###
# @name getContributionDetail
GET {{NEXT_PUBLIC_API_BASE_URL}}/contributions/{{contributionId}}
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

### ----------------- RETROACTIVE ------------------

###
# @name getRetroactiveAffectedUsersByPlanVersion
POST {{NEXT_PUBLIC_API_BASE_URL}}/contributions/retroactive/affected-users
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "planVersionId": "6d30e31f-4786-449b-978c-494747cd1715"
}

###
# @name getRetroactiveAffectedUsersByDate
POST {{NEXT_PUBLIC_API_BASE_URL}}/contributions/retroactive/affected-users
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "startDate": "2025-01-01",
  "endDate": "2026-12-31"
}
