@accountId =26921436-8d7b-4580-8b88-1f10778cd167
@entryId = REPLACE_WITH_ENTRY_ID
@userId = 7e534916-ffcc-467a-811a-b2544840777d

###
# @name listLedgerAccounts
GET {{NEXT_PUBLIC_API_BASE_URL}}/ledger/accounts
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

###
# @name createLedgerAccount
POST {{NEXT_PUBLIC_API_BASE_URL}}/ledger/accounts
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "name": "Membership Dues",
  "type": "INCOME",
  "code": "DUES-001"
}

###
# @name getLedgerAccount
GET {{NEXT_PUBLIC_API_BASE_URL}}/ledger/accounts/{{accountId}}
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

###
# @name deleteLedgerAccount
DELETE {{NEXT_PUBLIC_API_BASE_URL}}/ledger/accounts/{{accountId}}
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

###
# @name listLedgerEntries
GET {{NEXT_PUBLIC_API_BASE_URL}}/ledger/entries
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

###
# @name createLedgerEntry
POST {{NEXT_PUBLIC_API_BASE_URL}}/ledger/entries
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "accountId": "{{accountId}}",
  "type": "DEBIT",
  "amount": 1000,
  "description": "Monthly membership fee"
}

###
# @name approveLedgerEntry
POST {{NEXT_PUBLIC_API_BASE_URL}}/ledger/entries/{{entryId}}/approve
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

###
# @name getMemberLedger
GET {{NEXT_PUBLIC_API_BASE_URL}}/ledger/member/{{userId}}
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

###
# @name getLedgerSummary
GET {{NEXT_PUBLIC_API_BASE_URL}}/ledger/summary
Content-Type: application/json
Authorization: Bearer {{TOKEN}}
