@planId =f2a3ccb1-5756-467b-8132-e35b87d09f9e 
@subscriptionId = REPLACE_WITH_SUBSCRIPTION_ID
@userId=485796ba-8257-40c8-8999-c2b48203f1c3

###
# @name getSubscriptionPlans
GET {{NEXT_PUBLIC_API_BASE_URL}}/subscriptions/plans
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

###
# @name createSubscriptionPlan
POST {{NEXT_PUBLIC_API_BASE_URL}}/subscriptions/plans
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "name": "Test",
  "description": "Full access to all association benefits",
  "amount": 3000,
  "currency": "INR",
  "billingCycle": "MONTHLY",
  "effectiveTo":"2023-12-07",
  "features": {
    "events": true,
    "voting": true
  }
}

###
# @name subscribeToPlan
POST {{NEXT_PUBLIC_API_BASE_URL}}/subscriptions/subscribe
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "planId": "{{planId}}"
}

###
# @name waiveSubscription
POST {{NEXT_PUBLIC_API_BASE_URL}}/subscriptions/waive
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "subscriptionId": "{{subscriptionId}}",
  "reason": "Exempted by the board"
}

###
# @name getMySubscription
GET {{NEXT_PUBLIC_API_BASE_URL}}/subscriptions/my
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

###
# @name upgradeSubscription
POST {{NEXT_PUBLIC_API_BASE_URL}}/subscriptions/upgrade
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "planId": "{{planId}}",
  "userId":"{{userId}}"
}

###
# @name getSubscriptionPayments
GET {{NEXT_PUBLIC_API_BASE_URL}}/subscriptions/{{subscriptionId}}/payments
Content-Type: application/json
Authorization: Bearer {{TOKEN}}
