// This file was generated by Prisma, and assumes you have installed the following:
import 'dotenv/config';
import { defineConfig, env } from 'prisma/config';

export default defineConfig({
  schema: 'src/shared/lib/prisma/schema.prisma',
  migrations: {
    path: 'src/shared/lib/prisma/migrations',
    seed: 'node src/shared/lib/prisma/seed.ts',
  },
  datasource: {
    url: env('DATABASE_URL'),
  },
});
