export const AUTH = {
  SIGNUP: '/auth/sign-up',
  SIGNIN: '/auth/sign-in',
  SIGNIN_VERIFY: '/auth/sign-in/verify',
  SIGNIN_RESEND: '/auth/sign-in/resend',
  REFRESH: '/auth/refresh',
  FORGOT_PASSWORD: '/auth/forgot-password',
  RESET_PASSWORD: '/auth/reset-password',
  ME: '/auth/me',
  LOGOUT: '/auth/logout',
  CHANGE_PASSWORD: '/auth/change-password',
  MFA_SETUP: '/auth/mfa/setup',
  MFA_VERIFY: '/auth/mfa/verify',
  MFA_RESEND: '/auth/mfa/resend',
  MFA_DISABLE: '/auth/mfa/disable',
} as const;
